apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: quikit
  annotations:
    cloud.google.com/backend-config: '{"default": "quikit-backend-config"}'
spec:
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: NodePort