apiVersion: v1
kind: Service
metadata:
  name: ai-runtime-service
  namespace: quikit
spec:
  selector:
    app: ai-runtime
  ports:
  - protocol: TCP
    port: 8065
    targetPort: 8065
  type: NodePort
