apiVersion: v1
kind: Service
metadata:
  name: quikasset-service
  namespace: quikit
  annotations:
    cloud.google.com/backend-config: '{"default": "quikit-backend-config"}'
spec:
  selector:
    app: quikasset
  ports:
    - protocol: TCP
      port: 3012
      targetPort: 3012
  type: NodePort