apiVersion: v1
kind: Service
metadata:
  name: attendance-service
  namespace: quikit
spec:
  selector:
    app: attendance
  ports:
  - protocol: TCP
    port: 3022
    targetPort: 3022
  type: NodePort
