apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: quikit
  annotations:
    cloud.google.com/backend-config: '{"default": "quikit-backend-config"}'
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: NodePort