apiVersion: v1
kind: Service
metadata:
  name: crmexpress-service
  namespace: quikit
spec:
  selector:
    app: crmexpress
  ports:
  - protocol: TCP
    port: 3017
    targetPort: 3017
  type: NodePort
