apiVersion: v1
kind: Service
metadata:
  name: insights-service
  namespace: quikit
spec:
  selector:
    app: insights
  ports:
  - protocol: TCP
    port: 3015
    targetPort: 3015
  type: NodePort
