apiVersion: v1
kind: Service
metadata:
  name: quikfinance-service
  namespace: quikit
spec:
  selector:
    app: quikfinance
  ports:
  - protocol: TCP
    port: 3013
    targetPort: 3013
  type: NodePort
