apiVersion: v1
kind: Service
metadata:
  name: quiksocial-service
  namespace: quikit
  annotations:
    cloud.google.com/backend-config: '{"default": "quikit-backend-config"}'
spec:
  selector:
    app: quiksocial
  ports:
    - protocol: TCP
      port: 3006
      targetPort: 3006
  type: NodePort