apiVersion: v1
kind: Service
metadata:
  name: quiktrack-service
  namespace: quikit
  annotations:
    cloud.google.com/backend-config: '{"default": "quikit-backend-config"}'
spec:
  selector:
    app: quiktrack
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: NodePort