apiVersion: v1
kind: Service
metadata:
  name: support-service
  namespace: quikit
  
spec:
  selector:
    app: support
  ports:
    - protocol: TCP
      port: 3010
      targetPort: 3010
  type: NodePort