apiVersion: v1
kind: Service
metadata:
  name: visionempregistration-service
  namespace: quikit
spec:
  selector:
    app: visionempregistration
  ports:
  - protocol: TCP
    port: 7010
    targetPort: 7010
  type: NodePort
