apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pg18-pooler
  namespace: db
spec:
  cluster:
    name: pg18-cluster

  instances: 2

  pgbouncer:
    poolMode: transaction

  template:
    spec:
      containers:
      - name: pgbouncer
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi